### PR TITLE
Allow auto-version based on build argument of 'latest'

### PR DESCRIPTION
**Pull request by mgroeninger**
Hi!
  I added a RUN line which tests to see if the build argument BDS_VERSION equals 'latest' and, if so, fetches the download page to identify the latest version.
I left it so that the version is static for now (since my ability to test things is limited at the moment).
Thanks!

### CODE REVIEW

**Comment by Roemer** [comment]
Thanks, I like that. Can you split the large command into multiple lines so it is a little bit more readable?

**Comment by mgroeninger** [comment]
Good idea.  Hopefully this commit is better for readability!  Please let me know if you'd like it to be formatted differently.

Thanks!

**Comment by mgroeninger** [comment]
While working on this a bit I noticed the curl command is out of order with the install of curl.  My last commit installs before it calls.

**Comment by Roemer** [comment]
Thanks a lot, I merged your changes

**Pull request merged**
